import Head from 'next/head';
import Link from 'next/link';

const LINKS: {path: string, label: string, references: string[] }[] = [
  { path: '/tutorials/infinite-ticker', label: 'infinite-ticker', references: ['https://www.youtube.com/watch?v=AYf3nhDmgzA&t=320s'] },
  { path: '/tutorials/emoji-cursor', label: 'emoji-cursor', references: ['https://www.youtube.com/watch?v=RTp8jquvh-c&t=128s'] },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>css tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {LINKS.map((link) => (
          <li key={link.label}>
            <Link href={link.path}>{link.label}</Link>
            <ul>
              {link.references.map((reference) => (
                <li key={reference}>
                  <Link href={reference}>
                    {reference}
                  </Link>
                </li>
              ))}
            </ul>
          </li>
        ))}
      </ul>
    </div>
  )
}
