import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>css tutorials</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <li>
        <Link href={'./tutorials/infinite-ticker'}>infinit-ticker</Link>
      </li>
    </div>
  )
}
